<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>,
        "Swissup_Codemirror/js/toggleCodeMirror": {}
    }
}
</script>
<div class="admin__field-control control" data-bind="scope: '<?= /* @noEscape */ $block->getScope() ?>'">
    <!-- ko if: hasTemplate() -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</div>
